#!php

<?php
include "./database.php";

echo "Host IP: ";
$host = trim(fgets(STDIN));
echo "Database User: ";
$db_user = trim(fgets(STDIN));
echo "Database password: ";
$db_pwd = trim(fgets(STDIN));
echo "Database port: ";
$port = trim(fgets(STDIN));
echo "\n";

create_database($host, $db_user, $db_pwd, $port);

?>
